package com.spring.dev.client;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.support.AbstractApplicationContext;

import com.spring.dev.config.HelloWorldConfig;
import com.spring.dev.domain.HelloWorld;


// AnnotationConfigApplicationContext creates Spring Application Context accepting input as our configuration class 
// annotated with @Configuration, registering all the beans generated by the configuration class in Spring runtime. 
// Once we got the context configured, we can use getBean method to fetch a specific bean from Spring application 
// context and perform some action on that

public class AppMainConfigrnClass
{

	public static void main(String args[])
	{
		AbstractApplicationContext context = new AnnotationConfigApplicationContext(
				HelloWorldConfig.class);
		HelloWorld bean = (HelloWorld) context.getBean("helloWorldBean");
		bean.sayHello("Spring 4");
		context.close();
	}

}
